#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 10 10:31:28 2019

@author: Priyanka Bhakuni
@Team: Spark
"""

contractions = {
"1 pc": "piece",
"1 pis": "piece",
"100 pic":"100 piece",
"pcs": "piece",
"one peace": "piece",
"pair piece": "piece",
"per piese" : "piece",
"pices" : "piece",
"1" : "piece",
"one pcs" : "piece",
"onepices" : "piece",
"piec" : "piece",
"1no" : "piece",
"number" : "piece",
"per piec" : "piece",
"1pc" : "piece",
"1piec" : "piece",
"no" : "piece",
"per pies" : "piece",
"1pi" : "piece",
"peic" : "piece",
"one" : "piece",
"one pc" : "piece",
"pice" : "piece",
"pic" : "piece",
"pi" : "piece",
"psc" : "piece",
"in" : "inch",
"onepic" : "piece",
"one peace" : "piece",
"1 piec" : "piece",
"1 pice" : "piece",
"pc" : "piece",
"ounc" : "ounce",
"one peac" : "piece",
"Pc" : "piece",
"1pcd" : "piece",
"singl" : "piece",
"single piec" : "piece",
"pair piec" : "piece",
"1 box" : "box",
"1 liter" : "ltr",
"1 ltr" : "ltr",
"1 set" : "set",
"1 unit" : "unit",
"each" : "per",
"kg" : "kilogram",
"kilogram onwards" : "kilogram",
"liter" : "ltr",
"litre" : "ltr",
"milliliter" : "millimeter",
"nos" : "number",
"pc_onwards" : "piece",
"peice" : "piece",
"per sq.ft." : "per square feet",
"piece onwards" : "piece",
"pieces" : "piece",
"square fee" : "square feet",
"unit onward" : "unit",
"units" : "unit",
"litr" : "ltr",
"meter" : "mtr",
"mtrs" : "mtr",
"1 piece" : "piece",
"tons" : "ton"
}

